version: '3'

services:
  todo-db:
    container_name: 'todo-db'
    build: ./todo-data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: always
    volumes:
      - 'todo-data:/var/lib/postgresql/data'
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'

  # todo-backend:
  #   build: ./todo-backend
  #   container_name: 'todo-backend'
  #   command: npm start
  #   environment:
  #     - DATABASE_HOST=todo-db #This env variable change in order to connect with todo-db container
  #   ports:
  #     - '${BACKEND_PORT}:${BACKEND_PORT}'
  #   links:
  #     - todo-db

volumes:
  todo-data:
